### ISSUE TITLE
changing default installation location from $HOME/bin

### ISSUE THREAD

**Issue by Bhupesh-V** [deepsourcelabs/cli#53]
**Is your feature request related to a problem? Please describe.**
So the script at https://deepsource.io/cli is not really opensourced, that's why reporting this here:

the default location space for linux systems is generally `$HOME/.local/bin/`
this has an advantage to make the command `deepsource` beng invoked from anywhere in the system since the bin location is included in `$PATH` by default.

**Describe the solution you'd like**
Either we export the `$HOME/bin` to users `$PATH` env or change the default installation location

**Comment by siddhant-deepsource** [comment]
Hey @Bhupesh-V 👋 

Thank you for this amazing suggestion. This will indeed be a great improvement. We have been working to add new features to the CLI and have added this to the project roadmap as well. We will surely implement and ship it in upcoming release.

Thanks 🙌

**Comment by siddhant-deepsource** [comment]
Hey @Bhupesh-V,

The CLI now supports an environment variable `BINDIR` which you can set to download the binary in a custom location (default is `./bin/deepsource`). Thus, in order to make sure it executes globally, you can now install it in the set `PATH` by supplying it as an environment variable.

Example :
```
BINDIR=~/.local/bin curl https://deepsource.io/cli | sh
```
